=== sheijk/Velox3D/velox/Workspace/BoostBuild/mbuild.dtd
<!--
 ! DTD for mbuild files
 !
 !-->


<!-- workspace element - root -->
<!ELEMENT workspace (requirements?, projects)
>
<!ATTLIST workspace
    name        CDATA       #REQUIRED
    rootdir     CDATA       ""
>

<!-- projects collection -->
<!ELEMENT projects  (project+)>

<!-- single project -->
<!ELEMENT project (requirements?, files?, dependencies?)
>
<!ATTLIST project
    type        (exe | lib | dll)   "exe"
    name        CDATA               #REQUIRED
>

<!-- requirements -->
<!ELEMENT requirements ANY
>

<!-- file list -->
<!ELEMENT files (file*)
>
<!ATTLIST files
>

<!-- single file -->
<!ELEMENT file (#PCDATA)
>

<!-- dependencies -->
<!ELEMENT dependencies (dep*)
>

<!-- single dependency -->
<!ELEMENT dep   (#PCDATA)
>
<!ATTLIST dep
    name        CDATA               #REQUIRED
    type        (exe | lib | dll)   "lib"
>

=== sheijk/Velox3D/velox/Workspace/mbuild.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE workspace SYSTEM "mbuild.dtd">
<workspace name="Velox" rootdir="">
  <projects xmlns:exsl="http://exslt.org/common">
    <project name="CoreLib" type="lib">
      <files>
        <file>../../Api/V3d/Core.h</file>
        <file>../../Api/V3d/Core/DebugUtils.h</file>
        <file>../../Api/V3d/Core/IVApplication.h</file>
        <file>../../Api/V3d/Core/IVMemoryManager.h</file>
        <file>../../Api/V3d/Core/MemManager.h</file>
        <file>../../Api/V3d/Core/RangeIter.h</file>
        <file>../../Api/V3d/Core/VAssert.h</file>
        <file>../../Api/V3d/Core/VBuild.h</file>
        <file>../../Api/V3d/Core/VCoreLib.h</file>
        <file>../../Api/V3d/Core/VException.h</file>
        <file>../../Api/V3d/Core/VIOStream.h</file>
        <file>../../Api/V3d/Core/VLogging.h</file>
        <file>../../Api/V3d/Core/VMemory.h</file>
        <file>../../Api/V3d/Core/VNamedObject.h</file>
        <file>../../Api/V3d/Core/VObjectKey.h</file>
        <file>../../Api/V3d/Core/VObjectRegistry.h</file>
        <file>../../Api/V3d/Core/VObjectRegistryExceptions.h</file>
        <file>../../Api/V3d/Core/VTypeInfo.h</file>
        <file>../../Api/V3d/Core/VTypes.h</file>
        <file>../../API/V3d/Core/Container/VArray2d.h</file>
        <file>../../Api/V3d/Core/Container/VList.h</file>
        <file>../../Api/V3d/Core/Modules/VModuleBase.h</file>
        <file>../../Api/V3d/Core/Modules/VModuleParams.h</file>
        <file>../../Api/V3d/Core/Modules/VVeloxApp.h</file>
        <file>../../Api/V3d/Core/RangeIter/IVRangeIteratorPolicy.h</file>
        <file>../../Api/V3d/Core/RangeIter/VEmptyPolicy.h</file>
        <file>../../Api/V3d/Core/RangeIter/VRangeIterator.h</file>
        <file>../../Api/V3d/Core/RangeIter/VSingleValueRangePolicy.h</file>
        <file>../../Api/V3d/Core/RangeIter/VSTLAccessorRangePolicy.h</file>
        <file>../../Api/V3d/Core/RangeIter/VSTLRangeDerefPolicy.h</file>
        <file>../../Api/V3d/Core/RangeIter/VSTLRangePolicy.h</file>
        <file>../../Api/V3d/Core/RangeIter/VSTLRangePolicyBase.h</file>
        <file>../../Api/V3d/Core/SmartPtr/VAutoPtr.h</file>
        <file>../../Api/V3d/Core/SmartPtr/VGuards.h</file>
        <file>../../Api/V3d/Core/SmartPtr/VServicePtr.h</file>
        <file>../../Api/V3d/Core/SmartPtr/VSharedPtr.h</file>
        <file>../../Api/V3d/Core/SmartPtr/VSharedPtr.inl</file>
        <file>../../Api/V3d/Core/Wrappers/VGenericUtils.h</file>
        <file>../../Api/V3d/Core/Wrappers/VString.h</file>
        <file>../../Source/Core/DebugUtils.cpp</file>
        <file>../../Source/Core/MemLocalSettings.h</file>
        <file>../../Source/Core/MemManager.cpp</file>
        <file>../../Source/Core/VIOStream.cpp</file>
        <file>../../Source/Core/VLogging.cpp</file>
        <file>../../Source/Core/VTypeInfo.cpp</file>
        <file>../../Source/Core/VVeloxApp.cpp</file>
        <file>../../Source/Core/Error/VAssert.cpp</file>
        <file>../../Source/Core/Error/VException.cpp</file>
        <file>../../Source/Core/ObjectRegistry/VNamedObject.cpp</file>
        <file>../../Source/Core/ObjectRegistry/VObjectKey.cpp</file>
        <file>../../Source/Core/ObjectRegistry/VObjectRegistry.cpp</file>
        <file>../../Source/Core/ObjectRegistry/VObjectRegistryExceptions.cpp</file>
        <file>../../Source/Core/Wrappers/VString.cpp</file>
      </files>
    </project>
    <project name="KernelLib" type="lib">
      <files>
        <file>../../Source/Kernel/VKernel.cpp</file>
        <file>../../Source/Kernel/VKernel.h</file>
        <file>../../Source/Kernel/VKernelException.h</file>
        <file>../../Source/Kernel/VKernelIniReader.cpp</file>
        <file>../../Source/Kernel/VKernelIniReader.h</file>
        <file>../../Source/Kernel/VServiceProxy.cpp</file>
        <file>../../Source/Kernel/VServiceProxy.h</file>
        <file>../../Source/Module/VeloxModule.cpp</file>
        <file>../../Source/XMLService/VXMLAttribute.cpp</file>
        <file>../../Source/XMLService/VXMLAttribute.h</file>
        <file>../../Source/XMLService/VXMLComment.cpp</file>
        <file>../../Source/XMLService/VXMLComment.h</file>
        <file>../../Source/XMLService/VXMLElement.cpp</file>
        <file>../../Source/XMLService/VXMLElement.h</file>
        <file>../../Source/XMLService/VXMLService.cpp</file>
        <file>../../Source/XMLService/VXMLService.h</file>
        <file>../../Source/XMLService/VXMLText.cpp</file>
        <file>../../Source/XMLService/VXMLText.h</file>
        <file>../../Source/XMLService/VXMLWriter.cpp</file>
        <file>../../Source/XMLService/VXMLWriter.h</file>
        <file>../../Source/XMLService/XmlServiceDLL.cpp</file>
        <file>../../Source/XMLService/TinyXML/tinystr.cpp</file>
        <file>../../Source/XMLService/TinyXML/tinystr.h</file>
        <file>../../Source/XMLService/TinyXML/tinyxml.cpp</file>
        <file>../../Source/XMLService/TinyXML/tinyxml.h</file>
        <file>../../Source/XMLService/TinyXML/tinyxmlerror.cpp</file>
        <file>../../Source/XMLService/TinyXML/tinyxmlparser.cpp</file>
        <file>../../Api/V3d/XML.h</file>
        <file>../../Api/V3d/Xml/IVXMLAttribute.h</file>
        <file>../../Api/V3d/Xml/IVXMLComment.h</file>
        <file>../../Api/V3d/Xml/IVXMLElement.h</file>
        <file>../../Api/V3d/Xml/IVXMLNode.h</file>
        <file>../../Api/V3d/Xml/IVXMLService.h</file>
        <file>../../Api/V3d/Xml/IVXMLText.h</file>
        <file>../../Api/V3d/Xml/IVXMLVisitor.h</file>
        <file>../../Api/V3d/Xml/IVXMLWriter.h</file>
        <file>../../Api/V3d/Xml/VXMLExceptions.h</file>
      </files>
    </project>
    <project name="VeloxLib" type="lib">
      <files>
        <file>../../API/V3d/BoostSignals.h</file>
        <file>../../API/V3d/CG.h</file>
        <file>../../API/V3d/Config.h</file>
        <file>../../API/V3d/Console.h</file>
        <file>../../API/V3d/Core.h</file>
        <file>../../API/V3d/Editor.h</file>
        <file>../../API/V3d/Entity.h</file>
        <file>../../API/V3d/Graphics.h</file>
        <file>../../API/V3d/Image.h</file>
        <file>../../API/V3d/Input.h</file>
        <file>../../API/V3d/OpenGL.h</file>
        <file>../../API/V3d/Property.h</file>
        <file>../../API/V3d/Resource.h</file>
        <file>../../API/V3d/Scene.h</file>
        <file>../../API/V3d/System.h</file>
        <file>../../API/V3d/Updater.h</file>
        <file>../../API/V3d/Vfs.h</file>
        <file>../../API/V3d/Window.h</file>
        <file>../../API/V3d/XML.h</file>
        <file>../../Api/V3d/Math/ArrayOps.h</file>
        <file>../../Api/V3d/Math/ArrayOps.inl</file>
        <file>../../Api/V3d/Math.h</file>
        <file>../../Api/V3d/Math/Numerics.h</file>
        <file>../../Api/V3d/Math/Numerics.inl</file>
        <file>../../Api/V3d/Math/TransformationOps.h</file>
        <file>../../Api/V3d/Math/VBoundingBox.h</file>
        <file>../../Api/V3d/Math/VBoundingSphere.h</file>
        <file>../../API/V3d/Math/VCCylinder.h</file>
        <file>../../Api/V3d/Math/VHalfRay.h</file>
        <file>../../Api/V3d/Math/VLine.h</file>
        <file>../../Api/V3d/Math/VMatrix.h</file>
        <file>../../Api/V3d/Math/VMatrixOps.h</file>
        <file>../../Api/V3d/Math/VPlane.h</file>
        <file>../../Api/V3d/Math/VQuaternion.h</file>
        <file>../../Api/V3d/Math/VQuaternionOps.h</file>
        <file>../../Api/V3d/Math/VRBTransform.h</file>
        <file>../../Api/V3d/Math/VRect.h</file>
        <file>../../Api/V3d/Math/VRect3D.h</file>
        <file>../../Api/V3d/Math/VVector.h</file>
        <file>../../Api/V3d/Math/VVectorBase.h</file>
        <file>../../Api/V3d/Math/VVectorOps.h</file>
        <file>../../Api/V3d/Resource/IVResourceManager.h</file>
        <file>../../Api/V3d/Resource/IVResourceType.h</file>
        <file>../../Api/V3d/Resource/ResourceExceptions.h</file>
        <file>../../Api/V3d/Resource/VResource.h</file>
        <file>../../Api/V3d/Resource/VResourceData.h</file>
        <file>../../Api/V3d/Resource/VResourceDataPtr.h</file>
        <file>../../Api/V3d/Resource/VResourceId.h</file>
        <file>../../Api/V3d/Resource/VTypedResourceData.h</file>
        <file>../../Api/V3d/Resource/Types/VFileName.h</file>
        <file>../../Api/V3d/Resource/Types/VTextFile.h</file>
        <file>../../Api/V3d/Scene/IVGraphicsPart.h</file>
        <file>../../Api/V3d/Scene/IVLightManager.h</file>
        <file>../../Api/V3d/Scene/IVRenderStepPart.h</file>
        <file>../../Api/V3d/Scene/IVSceneManagerPart.h</file>
        <file>../../Api/V3d/Scene/IVShapePart.h</file>
        <file>../../Api/V3d/Scene/IVShooting.h</file>
        <file>../../Api/V3d/Scene/VDefaultRenderStepPart.h</file>
        <file>../../Api/V3d/Scene/VMeshPart.h</file>
        <file>../../Api/V3d/Scene/VMeshPartBase.h</file>
        <file>../../Api/V3d/Scene/VModelPart.h</file>
        <file>../../Api/V3d/Scene/VNaiveSceneManagerPart.h</file>
        <file>../../Api/V3d/Scene/VSimpleShooting.h</file>
        <file>../../Api/V3d/Scene/Shootings/VMirrorShooting.h</file>
        <file>../../API/V3d/Scene/Shootings/VShadowMapShooting.h</file>
        <file>../../Api/V3d/Scene/Shootings/VShootingBase.h</file>
        <file>../../Api/V3d/Scene/Shapes/VArrowMeshPart.h</file>
        <file>../../Api/V3d/Scene/Shapes/VBoxMeshPart.h</file>
        <file>../../Api/V3d/Scene/Shapes/VCoordSysDisplayPart.h</file>
        <file>../../API/V3d/Scene/Shapes/VCylinderMeshPart.h</file>
        <file>../../API/V3d/Scene/Shapes/VFrustumVisPart.h</file>
        <file>../../Api/V3d/Scene/Shapes/VOrientationGridPart.h</file>
        <file>../../Api/V3d/Scene/Shapes/VPlaneMeshPart.h</file>
        <file>../../Api/V3d/Scene/Shapes/VSkyboxPart.h</file>
        <file>../../Api/V3d/Scene/Shapes/VSphereMeshPart.h</file>
        <file>../../Api/V3d/Scene/Shapes/VTerrainPart.h</file>
        <file>../../Api/V3d/Scene/Shapes/VTorusMeshPart.h</file>
